// components/StatsSection.js
export default function StatsSection() {
  const stats = [
    { value: "230+", description: "Startups Incubated" },
    { value: "50,000+", description: "Students Reached" },
    { value: "30 Cr+", description: "Revenue Generated By Startups" },
    { value: "10 Cr+", description: "Funds To Support Startup" },
    { value: "1,100+", description: "Employment Generated" },
    { value: "100+", description: "Annual Networking Events" },
  ];

  return (
    <section className="bg-[#15222B] text-white">
      {/* Red border at the top */}
      <div className="h-1 bg-primary"></div>

      <div className="container mx-auto  p-10">
        <div className="flex flex-col md:flex-row justify-between text-center">
          {stats.map((stat, index) => (
            <div key={index} className="mb-8 md:mb-0">
              <h3 className="text-4xl font-bold">{stat.value}</h3>
              <p className="text-gray-400 mt-2">{stat.description}</p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}
