"use client";
// components/StatsSection.js
import CountUp from "react-countup";
import { useInView } from "react-intersection-observer";

export default function StatsSection() {
  const stats = [
    { value: 230, suffix: "+", description: "Startups Incubated" },
    { value: 50000, suffix: "+", description: "Students Reached" },
    { value: 30, suffix: " Cr+", description: "Revenue Generated By Startups" },
    { value: 10, suffix: " Cr+", description: "Funds To Support Startup" },
    { value: 1100, suffix: "+", description: "Employment Generated" },
    { value: 100, suffix: "+", description: "Annual Networking Events" },
  ];

  // Set up intersection observer hook
  const { ref, inView } = useInView({
    triggerOnce: true, // Trigger animation only once
    threshold: 0.3, // When 30% of the component is visible
  });

  return (
    <section className="bg-[#15222B] text-white w-full" ref={ref}>
      {/* Red border at the top */}
      <div className="h-1 bg-primary"></div>

      <div className=" p-10 w-full">
        <div className="flex flex-col md:flex-row justify-between w-full text-center">
          {stats.map((stat, index) => (
            <div key={index} className="mb-8 md:mb-0 w-40 text-start">
              <h3 className="text-4xl font-bold text-start">
                {inView && (
                  <CountUp start={0} end={stat.value} duration={2.5} />
                )}
                {stat.suffix}
              </h3>
              <p className="text-gray-400 mt-2">{stat.description}</p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}
